---
title: "publication_figs"
author: "Jonathan Tay"
date: "December 15, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F,
                      message = F,
                      warning = F,
                      results = 'asis')
```


```{r}
# Load packages, define variables

library(tidyverse)
library(broom)
library(rpart)
library(stargazer)

extractP <- function(results) {
  p <- results[seq(2, length(results), 2)]
  p <- unlist(p)
  corr <- p.adjust(p)
  return(corr)
}

bin <- c("Sex", "Diabetes", "HF", "MI/Angina", "Side")
ord <- c("mRS_3m", "occl4", "pig3")
cont <- c("Age",
          "BslNIH",
          "tPAdelay",
          "CoreCBF30",
          "MismCBF30",
          "CoreCBV60",
          "MismCBV60")
vars <- c(bin, ord, cont)
sig <- 3

read_csv('../data/data_final.csv', na = "?") %>%
  select(vars) %>%
  drop_na(., BslNIH) %>%
  mutate(
    dead = mRS_3m == 6,
    poor = mRS_3m >= 5,
    moderate = mRS_3m <= 3,
    good = mRS_3m <= 2,
    excellent = mRS_3m <= 1
  ) %>%
  mutate_at(bin, funs(factor(.))) %>%
  mutate_at(ord, funs(ordered(.))) ->
  df

#summarise_at(cont, c("median", "IQR"), na.rm = T)

df %>%
  count(mRS_3m) %>%
  mutate(per = round(n / sum(n), sig) * 100) -> clinical

catVars <- c(bin, ord)
outVars <- c('dead', 'poor', 'moderate', 'good', 'excellent')

```

```{r}

# Univariate
catResults <- matrix(, nrow = length(catVars), ncol = 0)
contResults <- matrix(, nrow = length(cont), ncol = 0)
rownames(catResults) <- catVars
rownames(contResults) <- cont

for (outcome in outVars) {
  map(df[catVars], function(x)
    table(x, df[[outcome]])) %>%
    map(., function(x)
      chisq.test(x)) %>%
    map_df(., magrittr::extract, c('statistic', 'p.value')) ->
    x2
  catResults <- cbind(catResults, x2)
  
  map(df[cont], function(x)
    t.test(x ~ df[[outcome]])) %>%
    map_df(., magrittr::extract, c('statistic', 'p.value')) ->
    f
  contResults <- cbind(contResults, f)
}

map(df[catVars], function(x)
  table(x, df$mRS_3m)) %>%
  map(., function(x)
    chisq.test(x)) %>%
  map_df(., magrittr::extract, c('statistic', 'p.value')) -> x2
catResults <- cbind(catResults, x2)

map(df[cont], function(x) aov(x ~ df$mRS_3m)) %>%
  map(., function(x) tidy(x)) %>%
  map_df(., magrittr::extract, c('statistic', 'p.value')) %>%
  drop_na -> f
contResults <- cbind(contResults, f)

stargazer(contResults, summary=F, type='html',
          digits=3)
```


```{r}
x2p <- extractP(catResults)
tp <- extractP(contResults)

# select only ps, then correct with mutate

for (outcome in outVars) {
  paste(outcome, "Age + BslNIH + occl4 + pig3 + CoreCBF30 + MismCBF30",
        sep = " ~ ") %>%
  glm(., data=df, family=binomial) ->
  logit
  
  confint(logit) %>%
    exp() -> 
    ci

  logit %>%
    tidy() %>%
    mutate(or = exp(estimate)) %>%
    select(or, p.value) %>%
    cbind(., ci) %>%
    round(., sig) -> results

  #dplyr rearrange columns
}

x <- rpart(poor ~ CoreCBF30, data=df)
x$splits %>% as.tibble() %>% select(index)

df %>% mutate(binCore = CoreCBF30 < 66.85) -> test
x2 <- table(test$binCore, test$poor)
# plot hist of df$occl4

```